# 02. Python Foundation for Mathematical Operations
@Shengli (Bruce) Jiang, University of South Carolina

This notebook connects the mathematical ideas in the slides with NumPy and SciPy.

1. Arrays, matrices, and tensors
2. Matrix operations
3. Linear systems and rank
4. Norms, inner products, and distances
5. A molecular descriptor example

## 1. NumPy is a Good Friend

Python lists are general containers. NumPy arrays are designed for numerical data and vectorized operations.

### 1.1 List and array conversion

In [1]:
import numpy as np

lst = [0.1, 0.2, 0.3, 0.4]
print(lst, type(lst))

arr = np.array(lst)
print(arr, type(arr))

lst2 = arr.tolist()
print(lst2, type(lst2))

[0.1, 0.2, 0.3, 0.4] <class 'list'>
[0.1 0.2 0.3 0.4] <class 'numpy.ndarray'>
[0.1, 0.2, 0.3, 0.4] <class 'list'>


Use a list for a small collection of general Python objects. Use a NumPy array when the data are numerical and you need array operations.

## 2. Vectors, Matrices, and Tensors

In NumPy, one array type represents vectors, matrices, and higher-dimensional data. The key properties are `ndim`, `shape`, and `size`.

### 2.1 Vectors

A vector in $\mathbb{R}^n$ can be stored as a one-dimensional array.

In [2]:
x = np.array([1.0, 2.0, 3.0])

print(x)
print("ndim:", x.ndim)
print("shape:", x.shape)
print("size:", x.size)

[1. 2. 3.]
ndim: 1
shape: (3,)
size: 3


### 2.2 Matrices and reshaping

A matrix has two axes. Flattening stacks its entries into a one-dimensional array. NumPy uses row-major order by default.

In [3]:
arr = np.array([[1, 3, 5],
                [2, 4, 6]])

print(arr)
print("-" * 20)
print(arr.flatten())

[[1 3 5]
 [2 4 6]]
--------------------
[1 3 5 2 4 6]


In [4]:
print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)

ndim: 2
shape: (2, 3)
size: 6


### 2.3 Higher-dimensional arrays

In machine learning, an array with $d$ axes is often called a rank-$d$ tensor. Here, rank means the number of axes, not matrix rank.

In [5]:
T = np.array([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])

print(T)
print("-" * 20)
print(T[0])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
--------------------
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
print("ndim:", T.ndim)
print("shape:", T.shape)
print("size:", T.size)

ndim: 3
shape: (3, 2, 5)
size: 30


## 3. Matrix Arithmetic

Elementwise operations and matrix operations answer different questions. Always check the shapes first.

### 3.1 Addition and scalar multiplication

Addition requires matching shapes. Scalar multiplication multiplies every entry by the same number.

In [7]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[8, 7],
              [6, 5]])

C = A + B
print(C)

[[9 9]
 [9 9]]


In [8]:
print(2 * A)

[[2 4]
 [6 8]]


### 3.2 Matrix multiplication

For $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times k}$, the product $AB$ has shape $m \times k$.

The four expressions below are equivalent for two-dimensional arrays.

In [9]:
print(np.matmul(A, B))
print(np.dot(A, B))
print(np.einsum('il,lj->ij', A, B))
print(A @ B)

[[20 17]
 [48 41]]
[[20 17]
 [48 41]]
[[20 17]
 [48 41]]
[[20 17]
 [48 41]]


Order matters in general. $AB$ and $BA$ can produce different results.

In [10]:
print(B @ A)

[[29 44]
 [21 32]]


### 3.3 Elementwise multiplication

Elementwise multiplication is also called the Hadamard product. Corresponding entries are multiplied.

In [11]:
print(A * B)
print(np.multiply(A, B))
print(np.einsum('ij,ij->ij', A, B))

[[ 8 14]
 [18 20]]
[[ 8 14]
 [18 20]]
[[ 8 14]
 [18 20]]


## 4. Transpose and Inverse

The transpose exchanges rows and columns. The inverse reverses a square, invertible linear transformation.

### 4.1 Inverse

In [12]:
A = np.array([[1, 2],
              [3, 4]])

print(A)
B = np.linalg.inv(A)
C = np.linalg.inv(B)
print(B)
print(C)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 2.]
 [3. 4.]]


In [13]:
print(np.allclose(A @ B, np.eye(2)))
print(np.allclose(B @ A, np.eye(2)))

True
True


### 4.2 Transpose

In [14]:
print(A.transpose())
print(A.T)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [15]:
print(np.allclose((A @ B).T, B.T @ A.T))

True


## 5. Solving Linear Systems

A linear system is written as $A\mathbf{x}=\mathbf{b}$. For a square, full-rank matrix, use `np.linalg.solve`.

### 5.1 A unique solution

In [16]:
A = np.array([[1, 2],
              [3, 4]])
b = np.array([6, 7])
x = np.linalg.solve(A, b)

print(x)
print(np.allclose(A @ x, b))

[-5.   5.5]
True


`solve` is preferred to explicitly computing $A^{-1}\mathbf{b}$. It is clearer and numerically more stable.

### 5.2 A singular system

The second row below is twice the first row, so the matrix is not full rank. `solve` reports a singular matrix.

In [17]:
A = np.array([[1, 2],
              [2, 4]])
b = np.array([3, 6])

try:
    x = np.linalg.solve(A, b)
except np.linalg.LinAlgError as error:
    print(type(error).__name__ + ":", error)

LinAlgError: Singular matrix


This particular system is consistent but has infinitely many solutions. `lstsq` returns one solution with minimum Euclidean norm.

In [18]:
x, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond=None)

print("x:", x)
print("rank:", rank)
print("Ax = b:", np.allclose(A @ x, b))

x: [0.6 1.2]
rank: 1
Ax = b: True


## 6. Rank and Independent Directions

Matrix rank is the number of linearly independent rows or columns. It measures how many independent directions the matrix contains.

### 6.1 Full rank and rank deficient

In [19]:
A = np.array([[1, 2],
              [3, 4]])
print("Rank of A:", np.linalg.matrix_rank(A))

B = np.array([[1, 2],
              [2, 4]])
print("Rank of B:", np.linalg.matrix_rank(B))

Rank of A: 2
Rank of B: 1


### 6.2 A reaction network

Each row is the stoichiometric change vector for one reaction. Negative entries are reactants and positive entries are products.

Species order is $[\mathrm{C},\mathrm{H_2O},\mathrm{CO},\mathrm{H_2},\mathrm{CO_2},\mathrm{CH_4}]$.

In [20]:
species = ["C", "H2O", "CO", "H2", "CO2", "CH4"]

A = np.array([
    [-1, -1,  1,  1,  0,  0],
    [-1, -2,  0,  2,  1,  0],
    [-1,  0,  0, -2,  0,  1],
    [-1,  0,  2,  0, -1,  0],
    [ 0, -1, -1,  1,  1,  0]
])

print(A)
print("rank:", np.linalg.matrix_rank(A))

[[-1 -1  1  1  0  0]
 [-1 -2  0  2  1  0]
 [-1  0  0 -2  0  1]
 [-1  0  2  0 -1  0]
 [ 0 -1 -1  1  1  0]]
rank: 3


Five listed reactions contain only three independent stoichiometric directions. Reactions 1, 3, and 5 form one possible independent set.

In [21]:
nu1, nu2, nu3, nu4, nu5 = A

print("nu2 = nu1 + nu5:", np.array_equal(nu2, nu1 + nu5))
print("nu4 = nu1 - nu5:", np.array_equal(nu4, nu1 - nu5))
print("rank of [nu1, nu3, nu5]:", np.linalg.matrix_rank(A[[0, 2, 4]]))

nu2 = nu1 + nu5: True
nu4 = nu1 - nu5: True
rank of [nu1, nu3, nu5]: 3


The rank does not say that only three physical reactions occur. It says that every net composition change generated by the five rows can be expressed using three independent change vectors.

## 7. Norms and Distances

A norm measures vector magnitude. A distance measures the magnitude of the difference between two vectors.

### 7.1 Manhattan and Euclidean norms

$$
\lVert \mathbf{x} \rVert_1=\sum_i |x_i|,
\qquad
\lVert \mathbf{x} \rVert_2=\sqrt{\sum_i x_i^2}
$$

In [22]:
x = np.array([3, 4])

l1 = np.linalg.norm(x, ord=1)
l2 = np.linalg.norm(x, ord=2)

print(l1)
print(l2)

7.0
5.0


### 7.2 The same total error can have a different pattern

Model A makes one large error. Model B spreads the error across four samples.

In [23]:
error_A = np.array([4, 0, 0, 0])
error_B = np.array([1, 1, 1, 1])

print("L1:", np.linalg.norm(error_A, 1), np.linalg.norm(error_B, 1))
print("L2:", np.linalg.norm(error_A, 2), np.linalg.norm(error_B, 2))

L1: 4.0 4.0
L2: 4.0 2.0


Both vectors have the same $L_1$ norm. The $L_2$ norm penalizes the concentrated error more strongly.

## 8. Inner Products and the Geometry They Define

An inner product compares two vectors. It also defines vector length, angle, projection, and distance.

### 8.1 The dot product

$$
\langle \mathbf{x},\mathbf{y}\rangle=\mathbf{x}^{T}\mathbf{y}
$$

In [24]:
x = np.array([1, 2])
y = np.array([3, 4])

print(np.dot(x, y))
print(x @ y)

11
11


### 8.2 A matrix-weighted inner product

For a symmetric positive-definite matrix $M$,

$$
\langle \mathbf{x},\mathbf{y}\rangle_M=\mathbf{x}^{T}M\mathbf{y}
$$

Symmetry gives the same comparison in either order. Positive definiteness ensures that every nonzero vector has positive squared length.

In [25]:
M = np.array([[1.0, -1.0],
              [-1.0, 2.0]])
x = np.array([2.0, 1.0])
y = np.array([1.0, 3.0])

inner_M = x @ M @ y
norm_M = np.sqrt(x @ M @ x)

print("symmetric:", np.allclose(M, M.T))
print("eigenvalues:", np.linalg.eigvalsh(M))
print("inner product:", inner_M)
print("weighted norm:", norm_M)

symmetric: True
eigenvalues: [0.38196601 2.61803399]
inner product: 1.0
weighted norm: 1.4142135623730951


### 8.3 From an inner product to a norm and distance

$$
\lVert \mathbf{x}\rVert=\sqrt{\langle\mathbf{x},\mathbf{x}\rangle},
\qquad
d(\mathbf{x},\mathbf{y})=\lVert\mathbf{x}-\mathbf{y}\rVert
$$

Every inner product defines a norm. Not every norm comes from an inner product. The $L_1$ norm is one important example.

In [26]:
x = np.array([1.0, 0.0])
y = np.array([0.0, 1.0])

left = np.linalg.norm(x + y, 1) ** 2 + np.linalg.norm(x - y, 1) ** 2
right = 2 * np.linalg.norm(x, 1) ** 2 + 2 * np.linalg.norm(y, 1) ** 2

print("parallelogram law, left:", left)
print("parallelogram law, right:", right)

parallelogram law, left: 8.0
parallelogram law, right: 4.0


The unequal values show that the $L_1$ norm cannot be generated by an inner product.

### 8.4 Euclidean and matrix-weighted distance

For $\mathbf{v}_1=[3,2]^T$ and $\mathbf{v}_2=[2,1]^T$, compare the usual Euclidean distance with the distance defined by $M$.

In [27]:
v1 = np.array([3.0, 2.0])
v2 = np.array([2.0, 1.0])
M = np.array([[1.0, -0.5],
              [-0.5, 1.0]])

delta = v1 - v2
d2 = np.sqrt(delta @ delta)
dM = np.sqrt(delta @ M @ delta)

print(d2)
print(dM)

1.4142135623730951
1.0


SciPy provides the same calculations. In `mahalanobis`, the third argument is the inverse covariance matrix. More generally, any symmetric positive-definite matrix defines this weighted distance.

In [28]:
from scipy.spatial.distance import euclidean, mahalanobis

d2 = euclidean(v1, v2)
dM = mahalanobis(v1, v2, M)

print(d2)
print(dM)

1.4142135623730951
1.0


### 8.5 Cauchy-Schwarz and vector angles

The Cauchy-Schwarz inequality keeps the normalized inner product between $-1$ and $1$. This allows us to define an angle.

$$
\cos\omega=\frac{\langle\mathbf{x},\mathbf{y}\rangle}{\lVert\mathbf{x}\rVert\lVert\mathbf{y}\rVert}
$$

In [29]:
x = np.array([1.0, 0.0])
y = np.array([1.0, 1.0])

cosine_similarity = (x @ y) / (np.linalg.norm(x) * np.linalg.norm(y))
angle = np.degrees(np.arccos(np.clip(cosine_similarity, -1.0, 1.0)))

print("cosine similarity:", cosine_similarity)
print("angle in degrees:", angle)

cosine similarity: 0.7071067811865475
angle in degrees: 45.00000000000001


### 8.6 Cosine distance

Cosine distance compares direction rather than magnitude.

$$
d_{\mathrm{cos}}(\mathbf{x},\mathbf{y})
=1-\frac{\mathbf{x}^{T}\mathbf{y}}{\lVert\mathbf{x}\rVert_2\lVert\mathbf{y}\rVert_2}
$$

In [30]:
from scipy.spatial.distance import cosine

d_cos = cosine(x, y)
print(d_cos)

angle = np.degrees(np.arccos(np.clip(1 - d_cos, -1.0, 1.0)))
print(angle)

0.29289321881345254
45.00000000000001


Cosine distance is useful when overall scale is not meaningful, such as comparing normalized spectra or document vectors. It is commonly called a distance, although it does not satisfy the triangle inequality in general.

### 8.7 Inner product checklist

A real-valued inner product must be linear, symmetric, and positive definite.

$$
\langle \mathbf{x},\mathbf{y}\rangle=\langle \mathbf{y},\mathbf{x}\rangle,
\qquad
\langle \mathbf{x},\mathbf{x}\rangle>0\text{ for }\mathbf{x}\ne\mathbf{0}
$$

## 9. Integrated Example with Molecular Descriptors

Suppose a small screening table represents each molecule with five descriptors.

| Molecule | Condensed structure | Formula |
|---|---|---|
| Methane | $\mathrm{CH_4}$ | $\mathrm{CH_4}$ |
| Ethane | $\mathrm{CH_3-CH_3}$ | $\mathrm{C_2H_6}$ |
| Methanol | $\mathrm{CH_3-OH}$ | $\mathrm{CH_4O}$ |
| Ethanol | $\mathrm{CH_3-CH_2-OH}$ | $\mathrm{C_2H_6O}$ |
| Dimethyl ether | $\mathrm{CH_3-O-CH_3}$ | $\mathrm{C_2H_6O}$ |
| Acetone | $\mathrm{CH_3-CO-CH_3}$ | $\mathrm{C_3H_6O}$ |
| Acetic acid | $\mathrm{CH_3-COOH}$ | $\mathrm{C_2H_4O_2}$ |
| Ethylene glycol | $\mathrm{HO-CH_2-CH_2-OH}$ | $\mathrm{C_2H_6O_2}$ |

Each row contains approximate molecular mass, carbon count, oxygen count, hydrogen-bond donors, and hydrogen-bond acceptors.

The query molecule is 1-propanol, $\mathrm{CH_3-CH_2-CH_2-OH}$. We will ask which listed molecule is closest to it. The answer will depend on both the representation and the distance.

### 9.1 Build the descriptor matrix

In [31]:
molecules = np.array([
    "methane", "ethane", "methanol", "ethanol",
    "dimethyl ether", "acetone", "acetic acid", "ethylene glycol"
])

features = np.array(["mass", "C", "O", "HBD", "HBA"])

X = np.array([
    [16, 1, 0, 0, 0],
    [30, 2, 0, 0, 0],
    [32, 1, 1, 1, 1],
    [46, 2, 1, 1, 1],
    [46, 2, 1, 0, 1],
    [58, 3, 1, 0, 1],
    [60, 2, 2, 1, 1],
    [62, 2, 2, 2, 2]
], dtype=float)

q = np.array([60, 3, 1, 1, 1], dtype=float)

print("features:", features)
print("shape:", X.shape)
print("rank:", np.linalg.matrix_rank(X))

features: ['mass' 'C' 'O' 'HBD' 'HBA']
shape: (8, 5)
rank: 5


The matrix has five independent descriptor columns. This does not mean that the descriptors are equally scaled or equally useful.

### 9.2 Raw Euclidean distance

Mass is numerically much larger than the count descriptors, so it dominates the raw distance.

In [32]:
delta_raw = X - q
d_raw = np.linalg.norm(delta_raw, axis=1)

order = np.argsort(d_raw)
for i in order[:3]:
    print(f"{molecules[i]:16s} {d_raw[i]:.3f}")

acetic acid      1.414
acetone          2.236
ethylene glycol  2.828


Acetic acid appears closest largely because it has the same approximate mass as 1-propanol.

### 9.3 Standardized Euclidean distance

Center each descriptor and divide by its sample standard deviation. The columns now have comparable numerical scales.

In [33]:
mean = X.mean(axis=0)
scale = X.std(axis=0, ddof=1)

Z = (X - mean) / scale
qz = (q - mean) / scale

d_scaled = np.linalg.norm(Z - qz, axis=1)

order = np.argsort(d_scaled)
for i in order[:3]:
    print(f"{molecules[i]:16s} {d_scaled[i]:.3f}")

acetone          1.349
ethanol          1.776
acetic acid      2.046


### 9.4 Cosine distance

Cosine distance compares descriptor direction. On raw descriptors, mass still strongly influences the direction.

In [34]:
d_cosine = np.array([cosine(q, row) for row in X])

order = np.argsort(d_cosine)
for i in order[:3]:
    print(f"{molecules[i]:16s} {d_cosine[i]:.6f}")

ethanol          0.000060
acetone          0.000140
dimethyl ether   0.000185


In [35]:
print("metric is symmetric:", np.allclose(M, M.T))
print("smallest eigenvalue:", np.linalg.eigvalsh(M).min())

metric is symmetric: True
smallest eigenvalue: 0.5


### 9.5 Compare the answers

In [36]:
distance_sets = {
    "raw Euclidean": d_raw,
    "scaled Euclidean": d_scaled,
    "cosine": d_cosine
}

for label, distances in distance_sets.items():
    i = np.argmin(distances)
    print(f"{label:25s} -> {molecules[i]}")

raw Euclidean             -> acetic acid
scaled Euclidean          -> acetone
cosine                    -> ethanol


The nearest molecule is not a property of the molecules alone. It is a result of the chosen descriptors, their scaling, and the distance metric.

This example combines arrays, matrix shape, rank, centering, scaling, norms, and distance calculations.